### ISSUE TITLE
XTSP min

### ISSUE THREAD

**Issue by dberlow** [googlefonts/roboto-flex-avar2#40]
All diagonals have more side bearing than the default.

wdth25 cannot be achieved without edits to this axis.
<img width="501" alt="Screenshot 2024-04-24 at 3 09 40 PM" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1956494/6e51a3da-2936-49fa-a929-14030bd15ea9">

**Comment by sannorozco** [comment]
I updated AKVWXY minimums.

If you see some overlapping it’s because of the kerning, we might need to add sparse kerning source for this location.

<img width="2233" alt="Screenshot 2024-04-24 at 14 06 22" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1184152/7c134bc2-4c74-4be2-bd35-5ede767f22bb">

<img width="2233" alt="Screenshot 2024-04-24 at 14 06 35" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1184152/3e4d6183-e3eb-448d-b254-d01843518dc2">

<img width="2233" alt="Screenshot 2024-04-24 at 14 06 39" src="https://github.com/googlefonts/roboto-flex-avar2/assets/1184152/8acd063c-a209-4c36-9e99-62001932c930">

**Comment by davelab6** [comment]
> we might need to add sparse kerning source for this location

Can this be closed?

**Comment by sannorozco** [comment]
Yes.
